import {
  Building2,
  CreditCard,
  Globe,
  LayoutGrid,
  Megaphone,
  Settings,
  Shield,
  Target,
  User,
  Users,
} from 'lucide-react-native';

import type {
  CostRow,
  FunnelInput,
  OpexColumn,
  Plan,
  ScenarioDefinition,
  ScenarioKey,
} from './types';

export const PLAN_KEYS: (keyof Plan)[] = [
  'year',
  'targetRevenue',
  'avgFee',
  'avgPrice',
  'costSaleCommission',
  'costMgmtCommission',
  'costMarketing',
  'costBonus',
  'costDiscount',
  'costOther',
  'hrSalaryBase',
  'hrSalaryOffice',
  'hrBonusBenefit',
  'hrRecruiting',
  'offRent',
  'offUtility',
  'offSupplies',
  'offMaintenance',
  'techEquipment',
  'techDepreciation',
  'techSoftware',
  'brandBranding',
  'brandHospitality',
  'legalFees',
  'legalConsulting',
  'legalInsurance',
  'legalOther',
  'rateDealBooking',
  'rateBookingMeeting',
  'rateMeetingLead',
  'salesSelfGenRate',
  'taxRate',
];

export const SCENARIOS: Record<ScenarioKey, ScenarioDefinition> = {
  BASE: { label: 'Thực tế', short: 'BASE', color: '#2563EB', revenue: 100, avgFee: 5.0, avgPrice: 5.0 },
  OPTIMISTIC: { label: 'Lạc quan', short: 'OPT', color: '#059669', revenue: 150, avgFee: 5.5, avgPrice: 5.5 },
  PESSIMISTIC: { label: 'Thận trọng', short: 'PES', color: '#D97706', revenue: 80, avgFee: 4.5, avgPrice: 4.5 },
};

export const DEFAULT_BY_SCENARIO: Record<ScenarioKey, Plan> = {
  BASE: {
    year: 2026,
    targetRevenue: 100,
    avgFee: 5,
    avgPrice: 5,
    costSaleCommission: 1.5,
    costMgmtCommission: 0.1,
    costMarketing: 0.3,
    costBonus: 0.2,
    costDiscount: 0.15,
    costOther: 0.1,
    hrSalaryBase: 200,
    hrSalaryOffice: 150,
    hrBonusBenefit: 20,
    hrRecruiting: 10,
    offRent: 50,
    offUtility: 5,
    offSupplies: 3,
    offMaintenance: 3,
    techEquipment: 5,
    techDepreciation: 10,
    techSoftware: 5,
    brandBranding: 15,
    brandHospitality: 20,
    legalFees: 2,
    legalConsulting: 5,
    legalInsurance: 0,
    legalOther: 5,
    rateDealBooking: 50,
    rateBookingMeeting: 30,
    rateMeetingLead: 20,
    salesSelfGenRate: 30,
    taxRate: 20,
  },
  OPTIMISTIC: {
    year: 2026,
    targetRevenue: 150,
    avgFee: 5.5,
    avgPrice: 5.5,
    costSaleCommission: 1.6,
    costMgmtCommission: 0.12,
    costMarketing: 0.35,
    costBonus: 0.22,
    costDiscount: 0.16,
    costOther: 0.1,
    hrSalaryBase: 230,
    hrSalaryOffice: 165,
    hrBonusBenefit: 25,
    hrRecruiting: 12,
    offRent: 55,
    offUtility: 6,
    offSupplies: 3,
    offMaintenance: 4,
    techEquipment: 6,
    techDepreciation: 12,
    techSoftware: 6,
    brandBranding: 20,
    brandHospitality: 25,
    legalFees: 3,
    legalConsulting: 6,
    legalInsurance: 0,
    legalOther: 6,
    rateDealBooking: 52,
    rateBookingMeeting: 32,
    rateMeetingLead: 22,
    salesSelfGenRate: 35,
    taxRate: 20,
  },
  PESSIMISTIC: {
    year: 2026,
    targetRevenue: 80,
    avgFee: 4.5,
    avgPrice: 4.5,
    costSaleCommission: 1.4,
    costMgmtCommission: 0.1,
    costMarketing: 0.25,
    costBonus: 0.15,
    costDiscount: 0.12,
    costOther: 0.08,
    hrSalaryBase: 180,
    hrSalaryOffice: 140,
    hrBonusBenefit: 15,
    hrRecruiting: 8,
    offRent: 45,
    offUtility: 5,
    offSupplies: 3,
    offMaintenance: 3,
    techEquipment: 4,
    techDepreciation: 9,
    techSoftware: 5,
    brandBranding: 10,
    brandHospitality: 15,
    legalFees: 2,
    legalConsulting: 5,
    legalInsurance: 0,
    legalOther: 5,
    rateDealBooking: 45,
    rateBookingMeeting: 28,
    rateMeetingLead: 18,
    salesSelfGenRate: 25,
    taxRate: 20,
  },
};

export const COST_ROWS: CostRow[] = [
  { label: 'Hoa hồng Sale', key: 'costSaleCommission', valueKey: 'sale', icon: User, color: '#2563EB' },
  { label: 'Hoa hồng Quản lý', key: 'costMgmtCommission', valueKey: 'mgr', icon: Users, color: '#4F46E5' },
  { label: 'Marketing', key: 'costMarketing', valueKey: 'mkt', icon: Megaphone, color: '#D97706' },
  { label: 'Thưởng nóng / Thi đua', key: 'costBonus', valueKey: 'bonus', icon: Target, color: '#E11D48' },
  { label: 'Chiết khấu khách hàng', key: 'costDiscount', valueKey: 'disc', icon: CreditCard, color: '#059669' },
  { label: 'Chi phí khác', key: 'costOther', valueKey: 'other', icon: LayoutGrid, color: '#64748B' },
];

export const OPEX_COLUMNS: OpexColumn[] = [
  {
    title: '1. Nhân sự & đào tạo',
    color: '#2563EB',
    icon: Users,
    items: [
      { label: 'Lương cơ bản Sales', key: 'hrSalaryBase' },
      { label: 'Lương khối văn phòng', key: 'hrSalaryOffice' },
      { label: 'Thưởng & phúc lợi', key: 'hrBonusBenefit' },
      { label: 'Tuyển dụng & đào tạo', key: 'hrRecruiting' },
    ],
  },
  {
    title: '2. Vận hành văn phòng',
    color: '#4F46E5',
    icon: Building2,
    items: [
      { label: 'Thuê mặt bằng', key: 'offRent' },
      { label: 'Điện, nước, internet', key: 'offUtility' },
      { label: 'VPP & in ấn', key: 'offSupplies' },
      { label: 'Bảo trì & vệ sinh', key: 'offMaintenance' },
    ],
  },
  {
    title: '3. Tài sản & công nghệ',
    color: '#7C3AED',
    icon: Settings,
    items: [
      { label: 'Mua sắm thiết bị', key: 'techEquipment' },
      { label: 'Khấu hao tài sản', key: 'techDepreciation' },
      { label: 'Phần mềm', key: 'techSoftware' },
    ],
  },
  {
    title: '4. Phát triển thương hiệu',
    color: '#F59E0B',
    icon: Globe,
    items: [
      { label: 'Branding thương hiệu', key: 'brandBranding' },
      { label: 'Tiếp khách & quà tặng', key: 'brandHospitality' },
    ],
  },
  {
    title: '5. Pháp lý & dự phòng',
    color: '#10B981',
    icon: Shield,
    items: [
      { label: 'Phí & lệ phí nhà nước', key: 'legalFees' },
      { label: 'Dịch vụ cố vấn', key: 'legalConsulting' },
      { label: 'Bảo hiểm', key: 'legalInsurance', auto: true },
      { label: 'Chi phí khác & dự phòng', key: 'legalOther' },
    ],
  },
];

export const FUNNEL_INPUTS: FunnelInput[] = [
  { label: 'Giá trị trung bình một giao dịch', key: 'avgPrice', unit: 'Tỷ', step: 0.1, precision: 1 },
  { label: 'Tỷ lệ Giao dịch / Giữ chỗ', key: 'rateDealBooking', unit: '%', step: 1, precision: 0 },
  { label: 'Tỷ lệ Giữ chỗ / Hẹn gặp', key: 'rateBookingMeeting', unit: '%', step: 1, precision: 0 },
  { label: 'Tỷ lệ Hẹn gặp / KHQT', key: 'rateMeetingLead', unit: '%', step: 1, precision: 0 },
];
